### ISSUE TITLE
Starting public docker swarm mode service issue with iptables #558

### ISSUE THREAD

**Issue by mohitsr76** [vmware/photon#583]
issue continuation from #558 

.. tried all of the above steps it still does not expose ports to outside.. 

curl -4 localhost  works 

but curl localhost hangs..

service not accessible from outside the container

kernel updated to 4.4.31

uname -a
Linux sw-mas 4.4.31 #1-photon SMP Tue Nov 22 15:06:04 UTC 2016 x86_64 GNU/Linux

any further suggestions ?

**Comment by YustasSwamp** [comment]
Can you show me `iptables -S` and `cat /etc/hosts`, please?

**Comment by mohitsr76** [comment]
as below,

root [ /home/boss ]# iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-N DOCKER
-N DOCKER-ISOLATION
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p udp -m udp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p udp -m udp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p udp -m udp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2377 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 7946 -j ACCEPT
-A INPUT -p udp -m udp --dport 7946 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 4789 -j ACCEPT
-A INPUT -p udp -m udp --dport 4789 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2375 -j ACCEPT
-A INPUT -p udp -m udp --dport 2375 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 6881 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 800 -j ACCEPT
-A INPUT -p udp -m udp --dport 800 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 800 -j ACCEPT
-A INPUT -p udp -m udp --dport 800 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A OUTPUT -j ACCEPT
-A DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP
-A DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -j RETURN


root [ /home/boss ]# cat /etc/hosts
# Begin /etc/hosts (network card version)

::1         localhost ipv6-localhost ipv6-loopback
127.0.0.1   localhost.localdomain
127.0.0.1	localhost
127.0.0.1	newpho
# End /etc/hosts (network card version)
127.0.0.1 sw-mas

**Comment by YustasSwamp** [comment]
1) remove "localhost" from ::1 in a first line of hosts file. First line should be "::1  ipv6-localhost ipv6-loopback"   (fixed in Photon OS)
2) iptables: allow input port for your service. Or allow any input port by default `iptables -P INPUT ACCEPT`

**Comment by YustasSwamp** [comment]
@mohitsr76 any updates?

**Comment by FlyingTom** [comment]
Hello, I've the same issue.
It works locally on my mac, but if I do the same on a Photon host, I'm not able to access the service using the published port. 

I tried what you proposed, but it does not solve the issue.

It is very strange because, if I do exactly the same commands on my mac, it works (init swarm, create service...).
Also, on the Photon host, if I create the same container without the swarm mode (docker run ...), the published port is accessible.

Any idea?

**Comment by FlyingTom** [comment]
The only difference I see between my local machine and the Photon host, is the version of the Docker engine.

Local machine: 1.12.5
Photon: 1.12.1

**Comment by FlyingTom** [comment]
If it can help, here is the result of "iptables --list" :

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            

Chain OUTPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            

Chain DOCKER (3 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere

**Comment by mohitsr76** [comment]
Hi Alex and Tom, 

the following helped me.

iptables -P FORWARD ACCEPT
iptables -P INPUT ACCEPT

this was a test setup so I accepted everything, but a selective ip table accept would need to be done for any practical purposes. 

its working now after what Alex suggested and  I did the ip tables forward accept.

Thanks

regards
mohit

**Comment by FlyingTom** [comment]
It seems to work, thanks!

**Comment by YustasSwamp** [comment]
good to know.
Thanks everyone.
